-- ════════════════════════════════════════════════════════════
-- 005_data_faqs_seed.sql
-- FAQ 84개 placeholder row (Phase 1.3)
-- 콘텐츠 4필드 (card_text / internal_data / wilson_note) = NULL
-- Step 1.6 매칭 엔진 빌드 시 .md 파싱하여 채움
-- 생성 도구: scripts/generate_seed_faqs.py
-- ════════════════════════════════════════════════════════════

BEGIN;

INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_검정고시_01_명문대_IELTS6.0이상_시드니_비즈니스', 'scenario', '검정고시', '검정고시 학생 시나리오: 명문대_IELTS6.0이상_시드니_비즈니스', '{"education": ["검정고시"], "major": ["비즈니스"], "english": ["6.0", "6.5", "7.0+"]}'::jsonb, 'ausuhak_faq/01_시나리오/01_검정고시/01_명문대_IELTS6.0이상_시드니_비즈니스.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_검정고시_02_명문대_IELTS5.5이하_시드니_비즈니스', 'scenario', '검정고시', '검정고시 학생 시나리오: 명문대_IELTS5.5이하_시드니_비즈니스', '{"education": ["검정고시"], "major": ["비즈니스"], "english": ["없음", "4.0-5.0", "5.5"]}'::jsonb, 'ausuhak_faq/01_시나리오/01_검정고시/02_명문대_IELTS5.5이하_시드니_비즈니스.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_검정고시_03_명문대_저예산_차선책', 'scenario', '검정고시', '검정고시 학생 시나리오: 명문대_저예산_차선책', '{"education": ["검정고시"]}'::jsonb, 'ausuhak_faq/01_시나리오/01_검정고시/03_명문대_저예산_차선책.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_검정고시_04_요리', 'scenario', '검정고시', '검정고시 학생 시나리오: 요리', '{"education": ["검정고시"], "major": ["요리·호텔"]}'::jsonb, 'ausuhak_faq/01_시나리오/01_검정고시/04_요리.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_검정고시_05_디자인', 'scenario', '검정고시', '검정고시 학생 시나리오: 디자인', '{"education": ["검정고시"], "major": ["디자인"]}'::jsonb, 'ausuhak_faq/01_시나리오/01_검정고시/05_디자인.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_검정고시_06_비즈니스_다양', 'scenario', '검정고시', '검정고시 학생 시나리오: 비즈니스_다양', '{"education": ["검정고시"], "major": ["비즈니스"]}'::jsonb, 'ausuhak_faq/01_시나리오/01_검정고시/06_비즈니스_다양.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_검정고시_07_Trade', 'scenario', '검정고시', '검정고시 학생 시나리오: Trade', '{"education": ["검정고시"], "major": ["Trade"]}'::jsonb, 'ausuhak_faq/01_시나리오/01_검정고시/07_Trade.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_검정고시_08_진로미정', 'scenario', '검정고시', '검정고시 학생 시나리오: 진로미정', '{"education": ["검정고시"], "major": ["미정"]}'::jsonb, 'ausuhak_faq/01_시나리오/01_검정고시/08_진로미정.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_검정고시_09_간호', 'scenario', '검정고시', '검정고시 학생 시나리오: 간호', '{"education": ["검정고시"], "major": ["간호"]}'::jsonb, 'ausuhak_faq/01_시나리오/01_검정고시/09_간호.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_고졸_01_학사_진학_시드니멜번', 'scenario', '고졸', '고졸 학생 시나리오: 학사_진학_시드니멜번', '{"education": ["고졸"]}'::jsonb, 'ausuhak_faq/01_시나리오/02_고졸/01_학사_진학_시드니멜번.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_고졸_02_요리호텔', 'scenario', '고졸', '고졸 학생 시나리오: 요리호텔', '{"education": ["고졸"], "major": ["요리·호텔"]}'::jsonb, 'ausuhak_faq/01_시나리오/02_고졸/02_요리호텔.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_고졸_03_Trade', 'scenario', '고졸', '고졸 학생 시나리오: Trade', '{"education": ["고졸"], "major": ["Trade"]}'::jsonb, 'ausuhak_faq/01_시나리오/02_고졸/03_Trade.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_고졸_04_디자인', 'scenario', '고졸', '고졸 학생 시나리오: 디자인', '{"education": ["고졸"], "major": ["디자인"]}'::jsonb, 'ausuhak_faq/01_시나리오/02_고졸/04_디자인.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_고졸_05_간호', 'scenario', '고졸', '고졸 학생 시나리오: 간호', '{"education": ["고졸"], "major": ["간호"]}'::jsonb, 'ausuhak_faq/01_시나리오/02_고졸/05_간호.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_고졸_06_진로미정', 'scenario', '고졸', '고졸 학생 시나리오: 진로미정', '{"education": ["고졸"], "major": ["미정"]}'::jsonb, 'ausuhak_faq/01_시나리오/02_고졸/06_진로미정.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_고졸_07_비즈니스', 'scenario', '고졸', '고졸 학생 시나리오: 비즈니스', '{"education": ["고졸"], "major": ["비즈니스"]}'::jsonb, 'ausuhak_faq/01_시나리오/02_고졸/07_비즈니스.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_고졸_08_IT', 'scenario', '고졸', '고졸 학생 시나리오: IT', '{"education": ["고졸"], "major": ["IT"]}'::jsonb, 'ausuhak_faq/01_시나리오/02_고졸/08_IT.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대학재학_01_휴학_어학연수', 'scenario', '대학재학', '대학재학 학생 시나리오: 휴학_어학연수', '{"education": ["대학재학"]}'::jsonb, 'ausuhak_faq/01_시나리오/03_대학재학/01_휴학_어학연수.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대학재학_02_졸업후_학사석사_진학', 'scenario', '대학재학', '대학재학 학생 시나리오: 졸업후_학사석사_진학', '{"education": ["대학재학"]}'::jsonb, 'ausuhak_faq/01_시나리오/03_대학재학/02_졸업후_학사석사_진학.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대학재학_03_편입_불가능_확인_대안', 'scenario', '대학재학', '대학재학 학생 시나리오: 편입_불가능_확인_대안', '{"education": ["대학재학"]}'::jsonb, 'ausuhak_faq/01_시나리오/03_대학재학/03_편입_불가능_확인_대안.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대학재학_04_어학연수_패스웨이', 'scenario', '대학재학', '대학재학 학생 시나리오: 어학연수_패스웨이', '{"education": ["대학재학"]}'::jsonb, 'ausuhak_faq/01_시나리오/03_대학재학/04_어학연수_패스웨이.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대졸PR_01_간호석사', 'scenario', '대졸PR', '대졸PR 학생 시나리오: 간호석사', '{"education": ["대졸PR"], "major": ["간호"]}'::jsonb, 'ausuhak_faq/01_시나리오/04_대졸PR/01_간호석사.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대졸PR_02_IT석사', 'scenario', '대졸PR', '대졸PR 학생 시나리오: IT석사', '{"education": ["대졸PR"], "major": ["IT"]}'::jsonb, 'ausuhak_faq/01_시나리오/04_대졸PR/02_IT석사.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대졸PR_03_회계석사_PY폐지반영', 'scenario', '대졸PR', '대졸PR 학생 시나리오: 회계석사_PY폐지반영', '{"education": ["대졸PR"], "major": ["비즈니스"]}'::jsonb, 'ausuhak_faq/01_시나리오/04_대졸PR/03_회계석사_PY폐지반영.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대졸PR_04_직업평가_PR', 'scenario', '대졸PR', '대졸PR 학생 시나리오: 직업평가_PR', '{"education": ["대졸PR"]}'::jsonb, 'ausuhak_faq/01_시나리오/04_대졸PR/04_직업평가_PR.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대졸PR_05_유아교육석사', 'scenario', '대졸PR', '대졸PR 학생 시나리오: 유아교육석사', '{"education": ["대졸PR"], "major": ["유아교육"]}'::jsonb, 'ausuhak_faq/01_시나리오/04_대졸PR/05_유아교육석사.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_대졸PR_06_공학석사', 'scenario', '대졸PR', '대졸PR 학생 시나리오: 공학석사', '{"education": ["대졸PR"], "major": ["공학"]}'::jsonb, 'ausuhak_faq/01_시나리오/04_대졸PR/06_공학석사.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_워홀러_01_PR전환', 'scenario', '워홀러', '워홀러 학생 시나리오: PR전환', '{"education": ["워홀러"]}'::jsonb, 'ausuhak_faq/01_시나리오/05_워홀러/01_PR전환.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_워홀러_02_비자연장', 'scenario', '워홀러', '워홀러 학생 시나리오: 비자연장', '{"education": ["워홀러"]}'::jsonb, 'ausuhak_faq/01_시나리오/05_워홀러/02_비자연장.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_워홀러_03_요리Trade', 'scenario', '워홀러', '워홀러 학생 시나리오: 요리Trade', '{"education": ["워홀러"], "major": ["요리·호텔"]}'::jsonb, 'ausuhak_faq/01_시나리오/05_워홀러/03_요리Trade.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_워홀러_04_학생비자전환', 'scenario', '워홀러', '워홀러 학생 시나리오: 학생비자전환', '{"education": ["워홀러"]}'::jsonb, 'ausuhak_faq/01_시나리오/05_워홀러/04_학생비자전환.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_조기유학_01_초등생_조기유학', 'scenario', '조기유학', '조기유학 학생 시나리오: 초등생_조기유학', '{"education": ["조기유학"]}'::jsonb, 'ausuhak_faq/01_시나리오/06_조기유학/01_초등생_조기유학.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_조기유학_02_중학생_조기유학', 'scenario', '조기유학', '조기유학 학생 시나리오: 중학생_조기유학', '{"education": ["조기유학"]}'::jsonb, 'ausuhak_faq/01_시나리오/06_조기유학/02_중학생_조기유학.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_조기유학_03_고등학생_조기유학', 'scenario', '조기유학', '조기유학 학생 시나리오: 고등학생_조기유학', '{"education": ["조기유학"]}'::jsonb, 'ausuhak_faq/01_시나리오/06_조기유학/03_고등학생_조기유학.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_조기유학_04_부모동반_가디언비자', 'scenario', '조기유학', '조기유학 학생 시나리오: 부모동반_가디언비자', '{"education": ["조기유학"]}'::jsonb, 'ausuhak_faq/01_시나리오/06_조기유학/04_부모동반_가디언비자.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('scenario_어학연수_01_ELICOS_종합', 'scenario', '어학연수', '어학연수 학생 시나리오: ELICOS_종합', '{"education": ["어학연수"]}'::jsonb, 'ausuhak_faq/01_시나리오/07_어학연수/01_ELICOS_종합.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_USyd', 'school', 'G8', '학교 정보: USyd (G8)', NULL, 'ausuhak_faq/02_학교_모듈/G8/01_USyd.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Melbourne', 'school', 'G8', '학교 정보: Melbourne (G8)', NULL, 'ausuhak_faq/02_학교_모듈/G8/02_Melbourne.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_UNSW', 'school', 'G8', '학교 정보: UNSW (G8)', NULL, 'ausuhak_faq/02_학교_모듈/G8/03_UNSW.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Monash', 'school', 'G8', '학교 정보: Monash (G8)', NULL, 'ausuhak_faq/02_학교_모듈/G8/04_Monash.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_UQ', 'school', 'G8', '학교 정보: UQ (G8)', NULL, 'ausuhak_faq/02_학교_모듈/G8/05_UQ.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_UWA', 'school', 'G8', '학교 정보: UWA (G8)', NULL, 'ausuhak_faq/02_학교_모듈/G8/06_UWA.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_ANU', 'school', 'G8', '학교 정보: ANU (G8)', NULL, 'ausuhak_faq/02_학교_모듈/G8/07_ANU.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Adelaide', 'school', 'G8', '학교 정보: Adelaide (G8)', NULL, 'ausuhak_faq/02_학교_모듈/G8/08_Adelaide.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_QUT', 'school', '기타_지방', '학교 정보: QUT (기타_지방)', NULL, 'ausuhak_faq/02_학교_모듈/기타_지방/01_QUT.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Griffith', 'school', '기타_지방', '학교 정보: Griffith (기타_지방)', NULL, 'ausuhak_faq/02_학교_모듈/기타_지방/02_Griffith.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Curtin', 'school', '기타_지방', '학교 정보: Curtin (기타_지방)', NULL, 'ausuhak_faq/02_학교_모듈/기타_지방/03_Curtin.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_UTAS', 'school', '기타_지방', '학교 정보: UTAS (기타_지방)', NULL, 'ausuhak_faq/02_학교_모듈/기타_지방/04_UTAS.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_UniSA', 'school', '기타_지방', '학교 정보: UniSA (기타_지방)', NULL, 'ausuhak_faq/02_학교_모듈/기타_지방/05_UniSA.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_ECU', 'school', '기타_지방', '학교 정보: ECU (기타_지방)', NULL, 'ausuhak_faq/02_학교_모듈/기타_지방/06_ECU.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Canberra', 'school', '기타_지방', '학교 정보: Canberra (기타_지방)', NULL, 'ausuhak_faq/02_학교_모듈/기타_지방/07_Canberra.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_JCU', 'school', '기타_지방', '학교 정보: JCU (기타_지방)', NULL, 'ausuhak_faq/02_학교_모듈/기타_지방/08_JCU.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_RMIT', 'school', '멜번_차선책', '학교 정보: RMIT (멜번_차선책)', NULL, 'ausuhak_faq/02_학교_모듈/멜번_차선책/01_RMIT.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Deakin', 'school', '멜번_차선책', '학교 정보: Deakin (멜번_차선책)', NULL, 'ausuhak_faq/02_학교_모듈/멜번_차선책/02_Deakin.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_LaTrobe', 'school', '멜번_차선책', '학교 정보: LaTrobe (멜번_차선책)', NULL, 'ausuhak_faq/02_학교_모듈/멜번_차선책/03_LaTrobe.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Swinburne', 'school', '멜번_차선책', '학교 정보: Swinburne (멜번_차선책)', NULL, 'ausuhak_faq/02_학교_모듈/멜번_차선책/04_Swinburne.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_UTS', 'school', '시드니_차선책', '학교 정보: UTS (시드니_차선책)', NULL, 'ausuhak_faq/02_학교_모듈/시드니_차선책/01_UTS.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Macquarie', 'school', '시드니_차선책', '학교 정보: Macquarie (시드니_차선책)', NULL, 'ausuhak_faq/02_학교_모듈/시드니_차선책/02_Macquarie.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_Wollongong', 'school', '시드니_차선책', '학교 정보: Wollongong (시드니_차선책)', NULL, 'ausuhak_faq/02_학교_모듈/시드니_차선책/03_Wollongong.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('school_WesternSydney', 'school', '시드니_차선책', '학교 정보: WesternSydney (시드니_차선책)', NULL, 'ausuhak_faq/02_학교_모듈/시드니_차선책/04_WesternSydney.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('region_시드니', 'region', '시드니', '지역 정보: 시드니', '{"preferred_region": ["시드니"]}'::jsonb, 'ausuhak_faq/03_지역_모듈/01_시드니.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('region_멜번', 'region', '멜번', '지역 정보: 멜번', '{"preferred_region": ["멜번"]}'::jsonb, 'ausuhak_faq/03_지역_모듈/02_멜번.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('region_브리즈번', 'region', '브리즈번', '지역 정보: 브리즈번', '{"preferred_region": ["브리즈번"]}'::jsonb, 'ausuhak_faq/03_지역_모듈/03_브리즈번.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('region_골드코스트', 'region', '골드코스트', '지역 정보: 골드코스트', '{"preferred_region": ["골드코스트"]}'::jsonb, 'ausuhak_faq/03_지역_모듈/04_골드코스트.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('region_퍼스', 'region', '퍼스', '지역 정보: 퍼스', '{"preferred_region": ["퍼스"]}'::jsonb, 'ausuhak_faq/03_지역_모듈/05_퍼스.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('region_애들레이드', 'region', '애들레이드', '지역 정보: 애들레이드', '{"preferred_region": ["애들레이드"]}'::jsonb, 'ausuhak_faq/03_지역_모듈/06_애들레이드.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('region_호바트', 'region', '호바트', '지역 정보: 호바트', '{"preferred_region": ["호바트"]}'::jsonb, 'ausuhak_faq/03_지역_모듈/07_호바트.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('region_캔버라', 'region', '캔버라', '지역 정보: 캔버라', '{"preferred_region": ["캔버라"]}'::jsonb, 'ausuhak_faq/03_지역_모듈/08_캔버라.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_간호', 'major', '간호', '전공 정보: 간호', '{"major": ["간호"]}'::jsonb, 'ausuhak_faq/04_전공_모듈/01_간호.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_IT', 'major', 'IT', '전공 정보: IT', '{"major": ["IT"]}'::jsonb, 'ausuhak_faq/04_전공_모듈/02_IT.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_비즈니스', 'major', '비즈니스', '전공 정보: 비즈니스', '{"major": ["비즈니스"]}'::jsonb, 'ausuhak_faq/04_전공_모듈/03_비즈니스.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_공학', 'major', '공학', '전공 정보: 공학', '{"major": ["공학"]}'::jsonb, 'ausuhak_faq/04_전공_모듈/04_공학.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_요리호텔', 'major', '요리호텔', '전공 정보: 요리호텔', '{"major": ["요리·호텔"]}'::jsonb, 'ausuhak_faq/04_전공_모듈/05_요리호텔.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_유아교육', 'major', '유아교육', '전공 정보: 유아교육', '{"major": ["유아교육"]}'::jsonb, 'ausuhak_faq/04_전공_모듈/06_유아교육.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_디자인', 'major', '디자인', '전공 정보: 디자인', '{"major": ["디자인"]}'::jsonb, 'ausuhak_faq/04_전공_모듈/07_디자인.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_Trade', 'major', 'Trade', '전공 정보: Trade', '{"major": ["Trade"]}'::jsonb, 'ausuhak_faq/04_전공_모듈/08_Trade.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_의료', 'major', '의료', '전공 정보: 의료', '{"major": ["의료"]}'::jsonb, 'ausuhak_faq/04_전공_모듈/09_의료.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('major_미정_추천', 'major', '미정_추천', '전공 정보: 미정_추천', NULL, 'ausuhak_faq/04_전공_모듈/10_미정_추천.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('visa_pr_학생비자_500', 'visa_pr', '학생비자_500', '비자/PR 정보: 학생비자_500', NULL, 'ausuhak_faq/05_비자PR_모듈/01_학생비자_500.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('visa_pr_485_졸업비자', 'visa_pr', '485_졸업비자', '비자/PR 정보: 485_졸업비자', NULL, 'ausuhak_faq/05_비자PR_모듈/02_485_졸업비자.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('visa_pr_PR경로_189_190_491', 'visa_pr', 'PR경로_189_190_491', '비자/PR 정보: PR경로_189_190_491', NULL, 'ausuhak_faq/05_비자PR_모듈/03_PR경로_189_190_491.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('visa_pr_GS_답변_가이드', 'visa_pr', 'GS_답변_가이드', '비자/PR 정보: GS_답변_가이드', NULL, 'ausuhak_faq/05_비자PR_모듈/04_GS_답변_가이드.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;
INSERT INTO internal_faqs (faq_id, module_type, category, question, matching_6vars, source_file, last_updated_at) VALUES ('visa_pr_직업평가', 'visa_pr', '직업평가', '비자/PR 정보: 직업평가', NULL, 'ausuhak_faq/05_비자PR_모듈/05_직업평가.md', '2026-05-04'::timestamp) ON CONFLICT (faq_id) DO NOTHING;

COMMIT;

-- ✅ TOTAL: 83 FAQ rows
-- Breakdown: scenario=36 / school=24 / region=8 / major=10 / visa_pr=5
-- 사양서 PART D-4 기대값: scenario=36 / school=24 / region=8 / major=10 / visa_pr=5 (총 84)