// AUTO-GENERATED by scripts/embed_master_to_src.py — DO NOT EDIT
// 정본: ausuhak_v25/02_DATABASE/ausuhak_master_v2_clean.json (Wilson 검수 2026-05-08)
import schoolsData from "./schools.json";
import blockingData from "./blocking_rules.json";
import alertsData from "./wilson_alerts.json";
import faqsData from "./faqs.json";

export type Program = {
  id?: string; name?: string; level?: string; duration?: string;
  tuition?: string | number; ielts?: string | number; entry?: string;
  pr_cat?: string; pr_grade?: string; campus?: string; note?: string;
};
export type School = {
  id: string; name: string; alts: string[]; type: string;
  city: string | null; state: string | null; campus: string | null;
  cricos: string | null; anmac: boolean | null;
  qs: number | null; founded: number | null; operator: string | null;
  programs: Program[];
};
export type BlockingRule = {
  id: string; severity: "hard" | "soft"; category: string; title: string;
  condition?: string | null; action: string;
  alternative?: string | null; wilson_reason?: string | null;
  raw: Record<string, unknown>;
};
export type WilsonAlert = {
  id: string; title?: string | null; quote?: string | null;
  principle?: string | null; truth?: string | null;
  applies_to?: string | null; marketing?: string | null;
  conditions: Record<string, unknown>;
};
export type FaqEntry = {
  id: string;
  type: "scenario" | "school" | "region" | "major" | "visa_pr";
  category?: string;
  card_text: string;
  wilson_note?: string;
  cards?: number[];
  required?: { schools: string[]; regions: string[]; majors: string[]; visa_pr: string[] };
  match?: { education: string[]; major: string[]; is_medical: boolean };
};

export const schools = schoolsData as School[];
export const blockingRules = blockingData as BlockingRule[];
export const wilsonAlerts = alertsData as WilsonAlert[];
export const faqs = faqsData as FaqEntry[];

// 인덱스 (매칭 성능)
export const schoolsByName: Record<string, School> = Object.fromEntries(schools.map((s) => [s.name, s]));
export const schoolsById: Record<string, School> = Object.fromEntries(schools.map((s) => [s.id, s]));
export const faqsByType: Record<string, FaqEntry[]> = faqs.reduce((acc, f) => {
  (acc[f.type] ||= []).push(f);
  return acc;
}, {} as Record<string, FaqEntry[]>);
